# Generated by Django 4.1.3 on 2022-12-06 06:19

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_answer_quiz_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', validators=[quiz.models.validate_answer]),
        ),
    ]
